### ISSUE TITLE
[Bug]: TbtData Creation Fail for empty bunch_ids and other remarks

### ISSUE THREAD

**Issue by JoschD** [pylhc/turn_by_turn#7]
### Documentation

- [X] Yes

### Operating System

Any

### Python Version

Any

### Package Version

0.3.0

### Bug Description

`TbtData` initialization is not working when giving empty bunch ids

https://github.com/pylhc/turn_by_turn/blob/45f728b576be1857e6ef33dd1893c6e2ad4edf5d/turn_by_turn/structures.py#L33-L51

`len(self.bunch_ids)` will fail with a `TypeError` as `None` has no length.

Writing is not working when `nturns` is not given, i.e. `0` but there is actually data,

### Steps to Reproduce

```python
import pandas as pd
from turn_by_turn import TbtData, TransverseData, write
import numpy as np

 # fails initializing
TbtData(matrices=[TransverseData(X=pd.DataFrame(np.random.random([4,5]),Y=pd.DataFrame([4,5]),),])

# fails writing
tbt = TbtData(matrices=[TransverseData(X=pd.DataFrame(np.random.random([4,5]),Y=pd.DataFrame([4,5]),),], bunch_ids=[])
write("test", tbt)
```

### Possible Fix Implementation

`self.nbunches = len(self.matrices)`
`nturns` should have no default, or default to `len(self.matrices[0].X.columns)`

but more remarks:
because of https://github.com/pylhc/sdds/issues/49 empty arrays can't be written anyway,
so maybe it should be

`self.bunch_ids = list(range(self.nbunches))`
?

**Comment by fsoubelet** [comment]
Closed with #9
