### ISSUE TITLE
[Bug]: Do not add '.sdds' if the file already ends with `.sdds`

### ISSUE THREAD

**Issue by JoschD** [pylhc/turn_by_turn#8]
### Documentation

- [X] Yes

### Operating System

Any

### Python Version

Any

### Package Version

0.3.0

### Bug Description

`.sdds` is automatically added to any filename. I don't think any other writer does this.

### Possible Fix Implementation

Change

https://github.com/pylhc/turn_by_turn/blob/45f728b576be1857e6ef33dd1893c6e2ad4edf5d/turn_by_turn/io.py#L97

to either 

`str(output_path.with_suffix('.sdds'))` 
which removes  other suffixes if present

or 

```python
if output_path.suffix != ".sdds":
    output_path = output_path.with_name(f"{output_path.name}.sdds")
```
(which keeps backwards compatibility)

or 

remove completely and let the user do whatever he wants with the output (my preferred choice)

**Comment by fsoubelet** [comment]
Closed with #9
